"""Outcome arbitrage strategy — trades mispriced HIP-4 prediction-market tokens.

Compares the market price of each price-binary outcome token against its
theoretical fair value (from the Black-Scholes digital option model) and
generates trade signals when the edge exceeds a configurable threshold.

Unlike the perp strategies (EMA, RSI, Breakout) which operate on OHLCV
DataFrames, this strategy operates on the pricing model output and works
in probability space (0-1).

Trade logic:
    1. For each price-binary outcome, compute theoretical Yes/No fair values
    2. Compare to live market mid prices
    3. If  edge = (theo - market) > min_edge   →  BUY  the cheap side
    4. If  edge = (market - theo) > min_edge   →  SELL the rich side
    5. Size the trade based on Kelly fraction of the edge
    6. Set take-profit when edge converges to 0, stop-loss at max_loss

Position management:
    - Max one position per outcome side
    - Auto-close when edge flips or approaches 0
    - Auto-close when T-to-expiry < min_time (avoid settlement risk)
    - Respects per-outcome and total portfolio exposure limits
"""
from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional, Tuple

from core.outcome_client import OutcomeClient, Outcome
from core.pricing_model import (
    PriceBinaryModel,
    BinaryPrice,
    price_binary,
    implied_vol,
    time_to_expiry_years,
    SECONDS_PER_YEAR,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Signal / position dataclasses
# ---------------------------------------------------------------------------

@dataclass
class ArbSignal:
    """A trade signal generated by the arb strategy."""
    outcome_id: int
    coin: str              # e.g. '#45570'
    side_label: str        # 'Yes' or 'No'
    action: str            # 'BUY', 'SELL', 'CLOSE', 'HOLD'
    edge: float            # theo - market (positive = cheap)
    theo: float            # theoretical fair value
    market: float          # market mid price
    strength: float        # 0-1, based on edge magnitude
    size: float            # suggested size in contracts
    limit_price: float     # suggested limit price
    reason: str = ""

    @property
    def is_actionable(self) -> bool:
        return self.action in ("BUY", "SELL")

    def __str__(self) -> str:
        return (
            f"{self.action} {self.size:.0f} {self.coin}({self.side_label}) "
            f"@ {self.limit_price:.4f}  "
            f"theo={self.theo:.4f} mkt={self.market:.4f} edge={self.edge:+.4f} "
            f"str={self.strength:.2f} | {self.reason}"
        )


@dataclass
class ArbPosition:
    """Tracks an open arb position."""
    outcome_id: int
    coin: str
    side_label: str
    is_buy: bool
    entry_price: float
    size: float
    entry_edge: float
    entry_time: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    oid: Optional[int] = None   # exchange order ID

    @property
    def side(self) -> str:
        return "BUY" if self.is_buy else "SELL"


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

@dataclass
class ArbConfig:
    """Configuration for the outcome arb strategy."""

    # Edge thresholds
    min_edge: float = 0.03          # minimum |edge| to open a trade (3 cents)
    close_edge: float = 0.005       # close when |edge| < this (edge converged)
    max_edge: float = 0.50          # ignore edges above this (likely stale data)

    # Sizing
    kelly_fraction: float = 0.25    # fraction of Kelly criterion to use
    max_size_per_outcome: float = 100.0   # max contracts per outcome side
    max_total_exposure: float = 500.0     # total across all outcomes
    base_size: float = 10.0         # minimum trade size

    # Risk
    max_loss_per_trade: float = 0.10      # max loss as fraction of position (10%)
    min_time_to_expiry_min: float = 2.0   # close if < N minutes to expiry
    max_positions: int = 10               # max concurrent arb positions

    # Pricing
    default_vol: float = 0.80       # fallback annualised vol
    vol_source: str = "auto"        # 'auto' (hist then default), 'fixed', 'implied'

    # Execution
    spread_buffer: float = 0.005    # offset from fair value for limit price
    use_ioc: bool = False           # True = IOC (market-like), False = GTC limit

    def __str__(self) -> str:
        return (
            f"ArbConfig(min_edge={self.min_edge}, kelly={self.kelly_fraction}, "
            f"max_size={self.max_size_per_outcome}, vol={self.default_vol})"
        )


# ---------------------------------------------------------------------------
# OutcomeArbStrategy
# ---------------------------------------------------------------------------

class OutcomeArbStrategy:
    """Detects mispriced outcome tokens vs theoretical value and generates trades.

    Usage::

        from core.outcome_client import OutcomeClient
        from core.pricing_model import PriceBinaryModel
        from strategies.outcome_arb import OutcomeArbStrategy, ArbConfig

        oc = OutcomeClient(testnet=True)
        model = PriceBinaryModel(oc)
        arb = OutcomeArbStrategy(oc, model, config=ArbConfig(min_edge=0.05))

        # Scan for opportunities
        signals = arb.scan()
        for sig in signals:
            print(sig)

        # Execute a signal (requires SDK Exchange)
        arb.execute(signals[0], exchange)
    """

    def __init__(
        self,
        outcome_client: OutcomeClient,
        pricing_model: PriceBinaryModel,
        config: Optional[ArbConfig] = None,
    ):
        self.oc = outcome_client
        self.model = pricing_model
        self.config = config or ArbConfig()

        # Open positions: coin -> ArbPosition
        self._positions: Dict[str, ArbPosition] = {}

        logger.info(f"OutcomeArbStrategy initialised: {self.config}")

    # ------------------------------------------------------------------
    # Sizing
    # ------------------------------------------------------------------

    def _kelly_size(self, edge: float, fair_value: float) -> float:
        """Calculate position size using fractional Kelly criterion.

        Kelly fraction for a binary bet:
            f* = (p * b - q) / b
        where p = probability of winning, b = odds, q = 1-p

        For outcome tokens priced at `market` with fair value `fair`:
            edge = fair - market
            p = fair  (probability of payout)
            b = (1 - market) / market  (payout odds)

        We use a fraction of full Kelly for safety.
        """
        if fair_value <= 0 or fair_value >= 1:
            return self.config.base_size

        # Odds of payout
        p = fair_value
        q = 1.0 - p
        market = fair_value - edge
        if market <= 0 or market >= 1:
            return self.config.base_size

        b = (1.0 - market) / market
        if b <= 0:
            return self.config.base_size

        kelly = (p * b - q) / b
        kelly = max(kelly, 0.0)

        # Apply fractional Kelly
        raw_size = kelly * self.config.kelly_fraction * self.config.max_size_per_outcome
        size = max(self.config.base_size, min(raw_size, self.config.max_size_per_outcome))

        return math.floor(size)  # outcome tokens are whole numbers

    def _check_exposure(self, additional_size: float) -> bool:
        """Check if adding a position would exceed exposure limits."""
        current = sum(p.size for p in self._positions.values())
        return (current + additional_size) <= self.config.max_total_exposure

    # ------------------------------------------------------------------
    # Signal generation
    # ------------------------------------------------------------------

    def _generate_signal(
        self,
        outcome: Outcome,
        analysis: PriceBinaryModel.AnalysisResult,
    ) -> List[ArbSignal]:
        """Generate arb signals for one outcome based on pricing analysis."""
        signals = []

        if analysis.market_yes is None:
            return signals

        # Check time to expiry
        if analysis.t_years <= 0:
            return signals
        mins_left = analysis.t_years * SECONDS_PER_YEAR / 60

        # --- Yes side ---
        if analysis.edge_yes is not None:
            edge = analysis.edge_yes
            theo = analysis.theory.fair_yes
            mkt = analysis.market_yes
            yes_coin = outcome.sides[0].coin if outcome.sides else None

            if yes_coin:
                sig = self._edge_to_signal(
                    outcome_id=outcome.outcome_id,
                    coin=yes_coin,
                    side_label="Yes",
                    edge=edge,
                    theo=theo,
                    market=mkt,
                    mins_left=mins_left,
                )
                if sig:
                    signals.append(sig)

        # --- No side ---
        if analysis.edge_no is not None and len(outcome.sides) > 1:
            edge = analysis.edge_no
            theo = analysis.theory.fair_no
            mkt = analysis.market_no
            no_coin = outcome.sides[1].coin

            if mkt is not None:
                sig = self._edge_to_signal(
                    outcome_id=outcome.outcome_id,
                    coin=no_coin,
                    side_label="No",
                    edge=edge,
                    theo=theo,
                    market=mkt,
                    mins_left=mins_left,
                )
                if sig:
                    signals.append(sig)

        return signals

    def _edge_to_signal(
        self,
        outcome_id: int,
        coin: str,
        side_label: str,
        edge: float,
        theo: float,
        market: float,
        mins_left: float,
    ) -> Optional[ArbSignal]:
        """Convert an edge observation into a trade signal."""
        abs_edge = abs(edge)
        cfg = self.config

        # Skip if edge too small or suspiciously large
        if abs_edge < cfg.min_edge:
            return None
        if abs_edge > cfg.max_edge:
            logger.debug(f"Edge too large for {coin}: {edge:.4f} (max={cfg.max_edge})")
            return None

        # Too close to expiry for new trades
        if mins_left < cfg.min_time_to_expiry_min:
            return None

        # Already have a position on this coin?
        existing = self._positions.get(coin)

        if existing:
            # Check if edge has flipped or converged → CLOSE
            if abs_edge < cfg.close_edge:
                return ArbSignal(
                    outcome_id=outcome_id,
                    coin=coin,
                    side_label=side_label,
                    action="CLOSE",
                    edge=edge,
                    theo=theo,
                    market=market,
                    strength=0.0,
                    size=existing.size,
                    limit_price=market,
                    reason=f"Edge converged ({edge:+.4f})",
                )
            # Edge flipped sign (was positive, now negative or vice versa)
            if (existing.entry_edge > 0 and edge < -cfg.close_edge) or \
               (existing.entry_edge < 0 and edge > cfg.close_edge):
                return ArbSignal(
                    outcome_id=outcome_id,
                    coin=coin,
                    side_label=side_label,
                    action="CLOSE",
                    edge=edge,
                    theo=theo,
                    market=market,
                    strength=0.0,
                    size=existing.size,
                    limit_price=market,
                    reason=f"Edge flipped ({existing.entry_edge:+.4f} -> {edge:+.4f})",
                )
            # Still in our favour — HOLD
            return None

        # New position
        if edge > cfg.min_edge:
            # Market is cheap -> BUY
            action = "BUY"
            limit_price = min(market + cfg.spread_buffer, theo)
            limit_price = max(0.001, min(0.999, limit_price))
        elif edge < -cfg.min_edge:
            # Market is rich -> SELL
            action = "SELL"
            limit_price = max(market - cfg.spread_buffer, theo)
            limit_price = max(0.001, min(0.999, limit_price))
        else:
            return None

        # Position count check
        if len(self._positions) >= cfg.max_positions:
            return None

        # Size
        size = self._kelly_size(abs_edge, theo)
        if not self._check_exposure(size):
            size = max(
                cfg.base_size,
                cfg.max_total_exposure - sum(p.size for p in self._positions.values())
            )
            if size < cfg.base_size:
                return None

        strength = min(abs_edge / 0.10, 1.0)  # full strength at 10 cents edge

        return ArbSignal(
            outcome_id=outcome_id,
            coin=coin,
            side_label=side_label,
            action=action,
            edge=edge,
            theo=theo,
            market=market,
            strength=strength,
            size=size,
            limit_price=round(limit_price, 5),
            reason=f"Edge {edge:+.4f} ({action} {side_label})",
        )

    # ------------------------------------------------------------------
    # Scan (main entry point)
    # ------------------------------------------------------------------

    def scan(
        self,
        vol: Optional[float] = None,
    ) -> List[ArbSignal]:
        """Scan all price-binary outcomes for arb opportunities.

        Args:
            vol: Override volatility for all outcomes. None = auto.

        Returns:
            List of actionable ArbSignals.
        """
        cfg = self.config
        v = vol if vol is not None else (
            cfg.default_vol if cfg.vol_source == "fixed" else None
        )

        analyses = self.model.analyse_all(vol=v, default_vol=cfg.default_vol)
        all_signals: List[ArbSignal] = []

        for analysis in analyses:
            outcome = self.oc.get_outcome(analysis.outcome_id)
            if outcome is None:
                continue

            signals = self._generate_signal(outcome, analysis)
            all_signals.extend(signals)

        # Also check existing positions for close signals (expiry, loss)
        close_signals = self._check_positions_for_close()
        all_signals.extend(close_signals)

        actionable = [s for s in all_signals if s.action != "HOLD"]
        if actionable:
            logger.info(f"Arb scan: {len(actionable)} actionable signal(s)")
            for s in actionable:
                logger.info(f"  {s}")

        return all_signals

    def _check_positions_for_close(self) -> List[ArbSignal]:
        """Check open positions for time-based or loss-based closes."""
        signals = []
        cfg = self.config

        for coin, pos in list(self._positions.items()):
            outcome = self.oc.get_outcome(pos.outcome_id)
            if outcome is None:
                continue

            # Time check
            if outcome.expiry:
                try:
                    t = time_to_expiry_years(outcome.expiry)
                    mins_left = t * SECONDS_PER_YEAR / 60
                    if mins_left < cfg.min_time_to_expiry_min:
                        mid = self._get_mid(coin)
                        signals.append(ArbSignal(
                            outcome_id=pos.outcome_id,
                            coin=coin,
                            side_label=pos.side_label,
                            action="CLOSE",
                            edge=0.0,
                            theo=0.0,
                            market=mid or pos.entry_price,
                            strength=1.0,
                            size=pos.size,
                            limit_price=mid or pos.entry_price,
                            reason=f"Expiry imminent ({mins_left:.1f}min left)",
                        ))
                except ValueError:
                    pass

            # Loss check
            mid = self._get_mid(coin)
            if mid is not None:
                if pos.is_buy:
                    pnl_pct = (mid - pos.entry_price) / pos.entry_price
                else:
                    pnl_pct = (pos.entry_price - mid) / pos.entry_price

                if pnl_pct < -cfg.max_loss_per_trade:
                    signals.append(ArbSignal(
                        outcome_id=pos.outcome_id,
                        coin=coin,
                        side_label=pos.side_label,
                        action="CLOSE",
                        edge=0.0,
                        theo=0.0,
                        market=mid,
                        strength=1.0,
                        size=pos.size,
                        limit_price=mid,
                        reason=f"Stop loss hit ({pnl_pct:+.1%})",
                    ))

        return signals

    def _get_mid(self, coin: str) -> Optional[float]:
        """Get current mid price for a coin."""
        try:
            mids = self.oc.fetch_outcome_mids()
            return mids.get(coin)
        except Exception:
            return None

    # ------------------------------------------------------------------
    # Execution
    # ------------------------------------------------------------------

    def execute(self, signal: ArbSignal, exchange=None) -> Optional[Dict]:
        """Execute a trade signal.

        Args:
            signal: The ArbSignal to execute.
            exchange: SDK Exchange instance (with outcome tokens injected).
                      If None, logs the signal but doesn't trade.

        Returns:
            Exchange response dict, or None if dry-run / no exchange.
        """
        if signal.action == "HOLD":
            return None

        if signal.action == "CLOSE":
            return self._execute_close(signal, exchange)

        if signal.action in ("BUY", "SELL"):
            return self._execute_open(signal, exchange)

        return None

    def _execute_open(self, signal: ArbSignal, exchange=None) -> Optional[Dict]:
        """Open a new arb position."""
        is_buy = signal.action == "BUY"

        logger.info(
            f"ARB OPEN: {signal.action} {signal.size:.0f} {signal.coin} "
            f"@ {signal.limit_price:.4f} (edge={signal.edge:+.4f})"
        )

        result = None
        if exchange is not None:
            try:
                tif = "Ioc" if self.config.use_ioc else "Gtc"
                result = exchange.order(
                    signal.coin,
                    is_buy,
                    signal.size,
                    signal.limit_price,
                    {"limit": {"tif": tif}},
                )
                logger.info(f"  Order result: {result}")
            except Exception as e:
                logger.error(f"  Order failed: {e}", exc_info=True)
                return None

        # Track position
        self._positions[signal.coin] = ArbPosition(
            outcome_id=signal.outcome_id,
            coin=signal.coin,
            side_label=signal.side_label,
            is_buy=is_buy,
            entry_price=signal.limit_price,
            size=signal.size,
            entry_edge=signal.edge,
        )

        return result

    def _execute_close(self, signal: ArbSignal, exchange=None) -> Optional[Dict]:
        """Close an existing arb position."""
        pos = self._positions.get(signal.coin)
        if pos is None:
            logger.warning(f"No position to close for {signal.coin}")
            return None

        logger.info(
            f"ARB CLOSE: {signal.coin} {pos.side} {pos.size:.0f} "
            f"@ {signal.limit_price:.4f} ({signal.reason})"
        )

        result = None
        if exchange is not None:
            try:
                # Close = opposite direction
                tif = "Ioc" if self.config.use_ioc else "Gtc"
                result = exchange.order(
                    signal.coin,
                    not pos.is_buy,  # reverse
                    pos.size,
                    signal.limit_price,
                    {"limit": {"tif": tif}},
                    reduce_only=True,
                )
                logger.info(f"  Close result: {result}")
            except Exception as e:
                logger.error(f"  Close failed: {e}", exc_info=True)
                return None

        # Remove tracked position
        del self._positions[signal.coin]
        return result

    def execute_all(self, signals: List[ArbSignal], exchange=None) -> List[Dict]:
        """Execute all actionable signals.

        Processes CLOSE signals first, then BUY/SELL.
        """
        results = []
        closes = [s for s in signals if s.action == "CLOSE"]
        opens = [s for s in signals if s.action in ("BUY", "SELL")]

        for s in closes + opens:
            r = self.execute(s, exchange)
            if r is not None:
                results.append(r)
        return results

    # ------------------------------------------------------------------
    # Status / reporting
    # ------------------------------------------------------------------

    @property
    def open_positions(self) -> Dict[str, ArbPosition]:
        """Currently tracked arb positions."""
        return dict(self._positions)

    @property
    def position_count(self) -> int:
        return len(self._positions)

    @property
    def total_exposure(self) -> float:
        return sum(p.size for p in self._positions.values())

    def summary(self) -> str:
        """Human-readable strategy status."""
        lines = [
            f"Outcome Arb Strategy",
            f"  Config: {self.config}",
            f"  Positions: {self.position_count} / {self.config.max_positions}",
            f"  Exposure: {self.total_exposure:.0f} / {self.config.max_total_exposure:.0f}",
        ]
        if self._positions:
            lines.append("  Open positions:")
            for coin, pos in self._positions.items():
                mid = self._get_mid(coin)
                pnl = ""
                if mid is not None:
                    if pos.is_buy:
                        pnl_val = (mid - pos.entry_price) * pos.size
                    else:
                        pnl_val = (pos.entry_price - mid) * pos.size
                    pnl = f" P&L={pnl_val:+.4f}"
                lines.append(
                    f"    {coin}({pos.side_label}): {pos.side} {pos.size:.0f} "
                    f"@ {pos.entry_price:.4f} edge={pos.entry_edge:+.4f}{pnl}"
                )
        return "\n".join(lines)

    def edge_summary(self, vol: Optional[float] = None) -> str:
        """Quick edge scan and summary (no execution)."""
        signals = self.scan(vol=vol)
        actionable = [s for s in signals if s.is_actionable]
        if not actionable:
            return "No arb opportunities found."
        lines = [f"Arb Opportunities ({len(actionable)}):"]
        for s in sorted(actionable, key=lambda x: abs(x.edge), reverse=True):
            lines.append(f"  {s}")
        return "\n".join(lines)
