"""HIP-4 Outcome monitor — watches for new markets, parses recurring contracts, sends alerts.

Runs a background polling thread (same pattern as NewsMonitor) that periodically
fetches outcome metadata and compares against a cached snapshot.  Fires callbacks
when:
    - A brand-new outcome appears
    - A new *recurring* price-binary contract spawns (e.g. the next 15m / 1d cycle)
    - An outcome's market price crosses a configurable threshold
    - An outcome is about to expire (configurable lead-time)

Integration points:
    - on_new_outcome   : fires for every newly-detected outcome
    - on_new_recurring : fires for new recurring price-binary contracts
    - on_expiry_warning: fires when T-to-expiry < threshold
    - on_price_cross   : fires when market price crosses a level
    - send_alert()     : dispatches to TelegramNotifier / EmailNotifier if wired
"""
from __future__ import annotations

import logging
import threading
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from typing import Callable, Dict, List, Optional, Set

from core.outcome_client import OutcomeClient, Outcome, PriceBinaryParsed
from core.pricing_model import (
    PriceBinaryModel,
    time_to_expiry_years,
    parse_expiry,
    SECONDS_PER_YEAR,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Alert dataclass
# ---------------------------------------------------------------------------

@dataclass
class OutcomeAlert:
    """A single alert generated by the monitor."""
    alert_type: str        # 'new_outcome', 'new_recurring', 'expiry_warning', 'price_cross'
    outcome_id: int
    message: str
    details: Dict = field(default_factory=dict)
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def __str__(self) -> str:
        ts = self.timestamp.strftime("%H:%M:%S")
        return f"[{ts}] {self.alert_type}: {self.message}"


# ---------------------------------------------------------------------------
# RecurringSpec — parsed info about a recurring contract series
# ---------------------------------------------------------------------------

@dataclass
class RecurringSpec:
    """Tracks a recurring price-binary contract series."""
    underlying: str
    period: str                # e.g. '1d', '15m', '1h'
    last_outcome_id: int
    last_expiry: str           # e.g. '20260420-0300'
    target_price: float
    first_seen: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    @property
    def series_key(self) -> str:
        """Unique key for this recurring series (underlying + period)."""
        return f"{self.underlying}:{self.period}"


# ---------------------------------------------------------------------------
# OutcomeMonitor
# ---------------------------------------------------------------------------

class OutcomeMonitor:
    """Background monitor for HIP-4 outcome markets.

    Polls the outcome API and detects:
      - New outcomes appearing
      - New recurring price-binary contracts (next cycle in a series)
      - Expiry warnings (approaching expiry)
      - Price threshold crossings

    Usage::

        from core.outcome_client import OutcomeClient
        from core.outcome_monitor import OutcomeMonitor

        oc = OutcomeClient(testnet=True)
        monitor = OutcomeMonitor(oc, poll_interval=30)

        monitor.on_new_outcome = lambda alert: print(alert)
        monitor.on_new_recurring = lambda alert: print(alert)

        monitor.start()
        # ... later ...
        monitor.stop()
    """

    def __init__(
        self,
        outcome_client: OutcomeClient,
        poll_interval: int = 30,
        expiry_warn_minutes: float = 5.0,
        price_cross_levels: Optional[Dict[str, List[float]]] = None,
    ):
        """
        Args:
            outcome_client: OutcomeClient instance for API calls.
            poll_interval: Seconds between polls.
            expiry_warn_minutes: Alert when T-to-expiry < this many minutes.
            price_cross_levels: Optional dict mapping coin -> list of price levels
                                to watch for crossings (e.g. {'#45570': [0.50, 0.80]}).
        """
        self.oc = outcome_client
        self.poll_interval = poll_interval
        self.expiry_warn_minutes = expiry_warn_minutes
        self.price_cross_levels = price_cross_levels or {}

        # State
        self._known_ids: Set[int] = set()          # outcome IDs we've already seen
        self._recurring: Dict[str, RecurringSpec] = {}  # series_key -> latest spec
        self._last_mids: Dict[str, float] = {}     # coin -> last known mid
        self._expiry_warned: Set[int] = set()       # outcome IDs already warned
        self._alerts: List[OutcomeAlert] = []       # alert history
        self._bootstrapped = False                   # first poll = silent bootstrap
        self._lock = threading.Lock()
        self._running = False
        self._thread: Optional[threading.Thread] = None

        # Callbacks — set these before calling start()
        self.on_new_outcome: Optional[Callable[[OutcomeAlert], None]] = None
        self.on_new_recurring: Optional[Callable[[OutcomeAlert], None]] = None
        self.on_expiry_warning: Optional[Callable[[OutcomeAlert], None]] = None
        self.on_price_cross: Optional[Callable[[OutcomeAlert], None]] = None
        self.on_any_alert: Optional[Callable[[OutcomeAlert], None]] = None

        # External notifiers (optional, set by dashboard or caller)
        self._telegram = None   # TelegramNotifier instance
        self._email = None      # EmailNotifier instance

    # ------------------------------------------------------------------
    # Notifier wiring
    # ------------------------------------------------------------------

    def set_telegram(self, telegram_notifier) -> None:
        """Wire a TelegramNotifier for alert dispatch."""
        self._telegram = telegram_notifier

    def set_email(self, email_notifier) -> None:
        """Wire an EmailNotifier for alert dispatch."""
        self._email = email_notifier

    def send_alert(self, alert: OutcomeAlert) -> None:
        """Dispatch an alert to Telegram / Email if configured."""
        emoji_map = {
            "new_outcome": "\U0001f195",      # 🆕
            "new_recurring": "\U0001f501",     # 🔁
            "expiry_warning": "\u23f0",        # ⏰
            "price_cross": "\U0001f4ca",       # 📊
        }
        emoji = emoji_map.get(alert.alert_type, "\U0001f514")  # 🔔

        text = (
            f"{emoji} *HIP-4 Alert: {alert.alert_type}*\n"
            f"{alert.message}\n"
            f"\U0001f552 {alert.timestamp.strftime('%Y-%m-%d %H:%M:%S UTC')}"
        )

        if self._telegram and self._telegram.enabled:
            try:
                self._telegram._send(text)
            except Exception as e:
                logger.error(f"Telegram alert failed: {e}")

        if self._email and self._email.enabled:
            try:
                subject = f"HIP-4 {alert.alert_type}: {alert.message[:60]}"
                body = f"<pre>{alert.message}</pre><br><small>{alert.timestamp}</small>"
                self._email._send(subject, body)
            except Exception as e:
                logger.error(f"Email alert failed: {e}")

    # ------------------------------------------------------------------
    # Detection logic
    # ------------------------------------------------------------------

    def _detect_new_outcomes(self, outcomes: List[Outcome]) -> List[OutcomeAlert]:
        """Detect brand-new outcomes that weren't in our known set."""
        alerts = []
        for o in outcomes:
            if o.outcome_id not in self._known_ids:
                if self._known_ids:  # skip first poll (bootstrap)
                    side_labels = ", ".join(f"{s.label}({s.coin})" for s in o.sides)
                    msg = (
                        f"New outcome #{o.outcome_id}: {o.question}\n"
                        f"Description: {o.description}\n"
                        f"Sides: {side_labels}"
                    )
                    alert = OutcomeAlert(
                        alert_type="new_outcome",
                        outcome_id=o.outcome_id,
                        message=msg,
                        details={
                            "question": o.question,
                            "description": o.description,
                            "underlying": o.underlying,
                            "target_price": o.target_price,
                            "expiry": o.expiry,
                            "period": o.period,
                        },
                    )
                    alerts.append(alert)
                self._known_ids.add(o.outcome_id)
        return alerts

    def _detect_recurring(self, outcomes: List[Outcome]) -> List[OutcomeAlert]:
        """Detect new recurring price-binary contracts.

        A 'recurring' contract is a priceBinary outcome where we've already
        seen a contract with the same underlying+period but a different
        outcome_id (meaning the platform spawned the next cycle).
        """
        alerts = []
        for o in outcomes:
            if o.underlying is None or o.period is None:
                continue

            series_key = f"{o.underlying}:{o.period}"
            existing = self._recurring.get(series_key)

            if existing is None:
                # First time seeing this series — register it
                self._recurring[series_key] = RecurringSpec(
                    underlying=o.underlying,
                    period=o.period,
                    last_outcome_id=o.outcome_id,
                    last_expiry=o.expiry or "",
                    target_price=o.target_price or 0.0,
                )
            elif existing.last_outcome_id != o.outcome_id:
                # New contract in this series!
                old_id = existing.last_outcome_id
                msg = (
                    f"New recurring contract: {o.underlying} {o.period}\n"
                    f"Outcome #{o.outcome_id} replaces #{old_id}\n"
                    f"Target: {o.target_price:,.2f}  Expiry: {o.expiry}"
                )
                alert = OutcomeAlert(
                    alert_type="new_recurring",
                    outcome_id=o.outcome_id,
                    message=msg,
                    details={
                        "underlying": o.underlying,
                        "period": o.period,
                        "target_price": o.target_price,
                        "expiry": o.expiry,
                        "previous_id": old_id,
                        "previous_expiry": existing.last_expiry,
                    },
                )
                alerts.append(alert)

                # Update tracker
                existing.last_outcome_id = o.outcome_id
                existing.last_expiry = o.expiry or ""
                existing.target_price = o.target_price or 0.0
        return alerts

    def _detect_expiry_warnings(self, outcomes: List[Outcome]) -> List[OutcomeAlert]:
        """Alert when a price-binary outcome is near expiry."""
        alerts = []
        now = datetime.now(timezone.utc)
        threshold_years = (self.expiry_warn_minutes * 60) / SECONDS_PER_YEAR

        for o in outcomes:
            if o.expiry is None or o.outcome_id in self._expiry_warned:
                continue
            try:
                t = time_to_expiry_years(o.expiry, now)
            except ValueError:
                continue

            if 0 < t < threshold_years:
                mins_left = t * SECONDS_PER_YEAR / 60
                msg = (
                    f"Expiry warning: {o.underlying or o.question} "
                    f"#{o.outcome_id} expires in {mins_left:.1f} min\n"
                    f"Target: {o.target_price}  Period: {o.period}"
                )
                alert = OutcomeAlert(
                    alert_type="expiry_warning",
                    outcome_id=o.outcome_id,
                    message=msg,
                    details={
                        "underlying": o.underlying,
                        "minutes_left": mins_left,
                        "target_price": o.target_price,
                        "expiry": o.expiry,
                    },
                )
                alerts.append(alert)
                self._expiry_warned.add(o.outcome_id)
        return alerts

    def _detect_price_crosses(self, mids: Dict[str, float]) -> List[OutcomeAlert]:
        """Alert when a price crosses a configured level."""
        alerts = []
        for coin, levels in self.price_cross_levels.items():
            new_price = mids.get(coin)
            old_price = self._last_mids.get(coin)
            if new_price is None or old_price is None:
                continue
            for level in levels:
                # Crossed up or down
                if (old_price < level <= new_price) or (old_price > level >= new_price):
                    direction = "above" if new_price >= level else "below"
                    msg = (
                        f"Price cross: {coin} moved {direction} {level:.4f}\n"
                        f"Price: {old_price:.4f} -> {new_price:.4f}"
                    )
                    alert = OutcomeAlert(
                        alert_type="price_cross",
                        outcome_id=0,
                        message=msg,
                        details={
                            "coin": coin,
                            "level": level,
                            "direction": direction,
                            "old_price": old_price,
                            "new_price": new_price,
                        },
                    )
                    alerts.append(alert)
        return alerts

    # ------------------------------------------------------------------
    # Poll cycle
    # ------------------------------------------------------------------

    def _poll_once(self) -> List[OutcomeAlert]:
        """Single polling cycle. Returns list of alerts generated."""
        all_alerts: List[OutcomeAlert] = []

        try:
            outcomes = self.oc.fetch_outcomes(force=True)
        except Exception as e:
            logger.error(f"Outcome monitor: fetch failed: {e}")
            return all_alerts

        # Bootstrap: silently populate known state on first poll
        if not self._bootstrapped:
            for o in outcomes:
                self._known_ids.add(o.outcome_id)
                if o.underlying and o.period:
                    series_key = f"{o.underlying}:{o.period}"
                    self._recurring[series_key] = RecurringSpec(
                        underlying=o.underlying,
                        period=o.period,
                        last_outcome_id=o.outcome_id,
                        last_expiry=o.expiry or "",
                        target_price=o.target_price or 0.0,
                    )
            try:
                self._last_mids = self.oc.fetch_outcome_mids()
            except Exception:
                pass
            self._bootstrapped = True
            logger.info(
                f"Outcome monitor bootstrapped: {len(self._known_ids)} outcomes, "
                f"{len(self._recurring)} recurring series"
            )
            return all_alerts

        # 1) New outcomes
        new_alerts = self._detect_new_outcomes(outcomes)
        all_alerts.extend(new_alerts)

        # 2) Recurring contracts
        recurring_alerts = self._detect_recurring(outcomes)
        all_alerts.extend(recurring_alerts)

        # 3) Expiry warnings
        expiry_alerts = self._detect_expiry_warnings(outcomes)
        all_alerts.extend(expiry_alerts)

        # 4) Price crosses
        try:
            mids = self.oc.fetch_outcome_mids()
            price_alerts = self._detect_price_crosses(mids)
            all_alerts.extend(price_alerts)
            self._last_mids = mids
        except Exception as e:
            logger.warning(f"Outcome monitor: mid fetch failed: {e}")

        # Store and dispatch alerts
        for alert in all_alerts:
            with self._lock:
                self._alerts.append(alert)
                # Cap history
                if len(self._alerts) > 1000:
                    self._alerts = self._alerts[-500:]

            # Fire specific callbacks
            try:
                if alert.alert_type == "new_outcome" and self.on_new_outcome:
                    self.on_new_outcome(alert)
                elif alert.alert_type == "new_recurring" and self.on_new_recurring:
                    self.on_new_recurring(alert)
                elif alert.alert_type == "expiry_warning" and self.on_expiry_warning:
                    self.on_expiry_warning(alert)
                elif alert.alert_type == "price_cross" and self.on_price_cross:
                    self.on_price_cross(alert)

                # Fire catch-all
                if self.on_any_alert:
                    self.on_any_alert(alert)
            except Exception as e:
                logger.error(f"Outcome monitor callback error: {e}")

            # Dispatch to Telegram / Email
            try:
                self.send_alert(alert)
            except Exception as e:
                logger.error(f"Outcome monitor alert dispatch error: {e}")

        if all_alerts:
            logger.info(
                f"Outcome monitor: {len(all_alerts)} alert(s) "
                f"[new={len(new_alerts)}, recurring={len(recurring_alerts)}, "
                f"expiry={len(expiry_alerts)}]"
            )
        return all_alerts

    # ------------------------------------------------------------------
    # Background loop
    # ------------------------------------------------------------------

    def _loop(self):
        """Background polling loop."""
        logger.info("Outcome monitor loop started")
        while self._running:
            try:
                self._poll_once()
            except Exception as e:
                logger.error(f"Outcome monitor poll error: {e}")
            # Sleep in small increments so stop() is responsive
            for _ in range(self.poll_interval):
                if not self._running:
                    break
                time.sleep(1)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Start background polling thread."""
        if self._running:
            return
        self._running = True
        self._thread = threading.Thread(
            target=self._loop, daemon=True, name="outcome-monitor"
        )
        self._thread.start()
        logger.info(
            f"Outcome monitor started (poll every {self.poll_interval}s, "
            f"expiry warn at {self.expiry_warn_minutes}min)"
        )

    def stop(self) -> None:
        """Stop polling."""
        self._running = False
        if self._thread:
            self._thread.join(timeout=5)
        logger.info("Outcome monitor stopped")

    @property
    def is_running(self) -> bool:
        return self._running

    def get_alerts(
        self,
        limit: int = 50,
        alert_type: Optional[str] = None,
    ) -> List[OutcomeAlert]:
        """Return recent alerts, newest first.

        Args:
            limit: Max alerts to return.
            alert_type: Filter by type (None = all).
        """
        with self._lock:
            if alert_type:
                filtered = [a for a in reversed(self._alerts) if a.alert_type == alert_type]
            else:
                filtered = list(reversed(self._alerts))
            return filtered[:limit]

    def get_recurring_series(self) -> Dict[str, RecurringSpec]:
        """Return all tracked recurring contract series."""
        return dict(self._recurring)

    def get_known_outcome_ids(self) -> Set[int]:
        """Return set of all known outcome IDs."""
        return set(self._known_ids)

    def add_price_watch(self, coin: str, level: float) -> None:
        """Add a price level to watch for crossings.

        Args:
            coin: Outcome coin (e.g. '#45570').
            level: Price level (0.0-1.0) to alert on crossing.
        """
        if coin not in self.price_cross_levels:
            self.price_cross_levels[coin] = []
        if level not in self.price_cross_levels[coin]:
            self.price_cross_levels[coin].append(level)
            logger.info(f"Watching {coin} for price cross at {level:.4f}")

    def remove_price_watch(self, coin: str, level: Optional[float] = None) -> None:
        """Remove a price watch.

        Args:
            coin: Outcome coin.
            level: Specific level to remove, or None to remove all for this coin.
        """
        if coin in self.price_cross_levels:
            if level is None:
                del self.price_cross_levels[coin]
            else:
                self.price_cross_levels[coin] = [
                    l for l in self.price_cross_levels[coin] if l != level
                ]

    def summary(self) -> str:
        """Human-readable status summary."""
        lines = [
            f"Outcome Monitor ({'RUNNING' if self._running else 'STOPPED'})",
            f"  Known outcomes: {len(self._known_ids)}",
            f"  Recurring series: {len(self._recurring)}",
            f"  Price watches: {sum(len(v) for v in self.price_cross_levels.values())}",
            f"  Total alerts: {len(self._alerts)}",
        ]
        if self._recurring:
            lines.append("  Active series:")
            for key, spec in self._recurring.items():
                lines.append(
                    f"    {key}: #{spec.last_outcome_id} "
                    f"target={spec.target_price:,.2f} exp={spec.last_expiry}"
                )
        return "\n".join(lines)
